export const VERSION = "2.0.0";
export const PREFIX = "RMRK";

export enum OP_TYPES {
  BUY = "BUY",
  LIST = "LIST",
  CREATE = "CREATE",
  MINT = "MINT",
  SEND = "SEND",
  EMOTE = "EMOTE",
  CHANGEISSUER = "CHANGEISSUER",
  CONSUME = "CONSUME",
  BASE = "BASE",
  EQUIPPABLE = "EQUIPPABLE",
  RESADD = "RESADD",
  ACCEPT = "ACCEPT",
  EQUIP = "EQUIP",
}
